resolver: lts-14.19

packages:
- .


extra-deps:
- stm-containers-1.1.0.4
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1

allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []